data_dir: "product_clustering_fluent2_bucket/tree/cactus/amazon_dataset" # Relative to hydra run dir
is_manifold: true
is_debug: false
is_override: false

base_url: "http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/"
category_list:
  - "Electronics"
  - "Office_Products"
  - "Clothing_Shoes_and_Jewelry"
  - "Digital_Music"
  - "Beauty"
  - "Home_and_Kitchen"
  - "Video_Games"
  - "Toys_and_Games"
  - "Books"

hydra:
  run:
    dir: /home/kbibas/cactus_outputs/download_data_${now:%Y%m%d_%H%M%S}
