# Data params
category: Clothing_Shoes_and_Jewelry
cf_vector_df_path: ../outputs/train_recommender_Clothing_Shoes_and_Jewelry_20211019_092258/cf_df.pkl
train_df_path: ../outputs/process_label_Clothing_Shoes_and_Jewelry_20211019_120707/df_train_with_pos.pkl
test_df_path: ../outputs/process_label_Clothing_Shoes_and_Jewelry_20211019_120707/df_test_with_pos.pkl

# Dataset params
seed: 1234
num_workers: 4
labeled_ratio: 1.0 # The ratio fo the traninig set to contain label
recall_at_k: [3, 5, 10]
# Optimization params
is_pretrained: true # Use imagenet pre trained model
cf_loss_type: triplet
batch_size: 128
weight_decay: 1e-5
lr: 1e-1
milestones: [55] 
epochs:  85

label_weight: 1.0 # The loss weight for binary label loss
cf_weight: 2.0  # The loss weight for cf vectors
cf_topk_loss_ratio: 1.0 # Consider only items with the lowest loss in the batch. 1.0 means consider all

# Flow params
is_debug: false
gpu: 0

# defaults:  
#   - override hydra/launcher: joblib

hydra:
  run:
    dir: ../outputs/train_model_${category}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ../outputs/train_model_multirun_${category}_${now:%Y%m%d_%H%M%S}
    subdir: train_model_${category}_${now:%Y%m%d_%H%M%S}_${hydra.job.num}
  # launcher:
  #   # override the number of jobs for joblib
  #   n_jobs: 8


#  python train_model.py -m cf_weight=0.0,1.0,2.0,10.0,20.0
#  python train_model.py -m cf_weight=0.0,2.0 labeled_ratio=0.5,0.6,0.7,0.8,0.9,1.0 
#  python train_model.py cf_topk_loss_ratio=0.9
#  python train_model.py -m cf_weight=1.0,2.0,10.0
#  python train_model.py -m cf_weight=2.0 labeled_ratio=0.5,0.6,0.7,0.8,0.9
#  python train_model.py -m cf_weight=0.0,1.0,2.0,10.0