# Data params
data_dir: /home/koby/datasets/amazon_dataset # Relative to hydra run dir
category: Clothing_Shoes_and_Jewelry
emb_size: 32

# Optimization params
batch_size: 4096
num_workers: 0 # Dataset is stored in GPU so no need for workers.
l2_reg: 1e-5 # Explicit add l2 regularization to the loss.
lr: 1.0
milestones: [100,150]
epochs: 200
num_negatives: 4
embedding_max_norm: 1.0 # null for ignore. The maximum allowed norm

# Flow params
seed: 1234
top_k_list: [1, 10, 20, 40 ,50]
is_debug: false
gpu: 0

hydra:
  run:
    dir: ../outputs/train_bpr_${now:%Y%m%d_%H%M%S}