# Data params
data_dir: /data/amazon_dataset
category: Toys_and_Games # Clothing_Shoes_and_Jewelry
emb_size: [64]
bottleneck_size: 32
test_size: 0.1
user_based: true

# Optimization params
batch_size: 4096
lr: 0.01
n_epochs: 100
beta: 1.0

# Flow params
seed: 1234
top_k_list: [5,10, 50]
gpu: 0

hydra:
  run:
    dir: ../outputs/${category}/train_recommender_${now:%Y%m%d_%H%M%S}