# Data params
data_dir: /data/amazon_dataset
category: Clothing_Shoes_and_Jewelry # Electronics/Clothing_Shoes_and_Jewelry
emb_size: 32

# Optimization params
batch_size: 4096
num_workers: 8 
weight_decay: 1e-5
lr: 1.0
milestones: [300, 400]
epochs: 500
weight_neg_items: 1e-4
drop_out_p: 0.05

# Flow params
seed: 1234
top_k_list: [1, 10, 20, 30, 40 ,50]
is_debug: false
gpu: 0

hydra:
  run:
    dir: /home/kbibas/cactus_outputs/train_autoencoder_${category}_${now:%Y%m%d_%H%M%S}

# Hyper-params:
# buck run @mode/dev-nosan :train_autoencoder -- -m gpu=1 lr=10.0,1.0,0.1
# buck run @mode/dev-nosan :train_autoencoder gpu=1 lr=0.1
