# Data params
category: Clothing_Shoes_and_Jewelry
cf_vector_df_path: ../outputs/train_recommender_Clothing_Shoes_and_Jewelry_20211007_103529/cf_df.pkl
label_df_path: ../outputs/process_label_Clothing_Shoes_and_Jewelry_20211007_122045/df_w_labels.pkl

# Dataset params
train_set_ratio: 0.75
seed: 1234
num_workers: 4
img_transform_resize: 256 # Aligned with imagenet
img_transform_crop: 224 # Aligned with imagenet
labeled_ratio: 1.0 # The ratio fo the traninig set to contain label

# Optimization params
is_pretrained: true
batch_size: 256
weight_decay: 1e-4
cf_weight: 0.0 # The loss weight for cf vectors
unfreeze_backbone_at_epoch: 5 # Epoch at which the backbone will be unfreezed.
backbone_initial_lr: 1e-3 # Inital learning rate for the backbone.
backbone_lr_multiplicative: 10 # Scheduling function for increasing backbone learning rate.
lr: 1e-1
milestones: [40, 80]
epochs: 100 
cf_topk_loss_ratio: 0.9 # Consider only items with the lowest loss in the batch. 1.0 means consider all

# Flow params
is_debug: false
gpu: 0

hydra:
  run:
    dir: ../outputs/train_model_${category}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ../outputs/train_model_multirun_${category}_${now:%Y%m%d_%H%M%S}
    subdir: train_model_${category}_${now:%Y%m%d_%H%M%S}_${hydra.job.num}
