# Data params
category: Clothing_Shoes_and_Jewelry
cf_vector_df_path: ../outputs/train_recommender_Clothing_Shoes_and_Jewelry_20211019_092258/cf_df.pkl
train_df_path: ../outputs/process_label_Clothing_Shoes_and_Jewelry_20211019_120707/df_train.pkl
test_df_path: ../outputs/process_label_Clothing_Shoes_and_Jewelry_20211019_120707/df_test.pkl

# Dataset params
seed: 1234
num_workers: 4
labeled_ratio: 1.0 # The ratio fo the traninig set to contain label

# Optimization params
is_pretrained: true # use imagenet pre trained model
batch_size: 256
weight_decay: 1e-5
lr: 1e-1
milestones: [50,100,140]
epochs: 150

cf_weight: 10 # The loss weight for cf vectors
cf_topk_loss_ratio: 1.0 # Consider only items with the lowest loss in the batch. 1.0 means consider all

# Flow params
is_debug: false
gpu: 0

hydra:
  run:
    dir: ../outputs/train_model_${category}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ../outputs/train_model_multirun_${category}_${now:%Y%m%d_%H%M%S}
    subdir: train_model_${category}_${now:%Y%m%d_%H%M%S}_${hydra.job.num}


#  python train_model.py -m cf_weight=0.0,1.0,2.0,10.0,20.0,100.0
