# Data params
category: Beauty # Clothing_Shoes_and_Jewelry/Home_and_Kitchen/Toys_and_Games/Beauty/movielens
cf_vector_df_path: ../outputs/${category}/cf_df.pkl
train_df_path: ../outputs/${category}/df_train.pkl
test_df_path: ../outputs/${category}/df_test.pkl
cf_based_train_loss_path: ../outputs/${category}/cf_based_train_loss.pt
cf_based_test_loss_path: ../outputs/${category}/cf_based_test_loss.pt
cf_embeddings_train_path: ../outputs/${category}/cf_embeddings_train.pt
cf_embeddings_test_path: ../outputs/${category}/cf_embeddings_test.pt

arch: resnet18 # resnet18/mobilenet

# Dataset params
seed: 1234
num_workers: 4
labeled_ratio: 1.0 # The ratio fo the traninig set to contain label
recall_at_k: []
is_use_bias: true
is_use_cf_embeddings: false
confidence_type: pos_label_loss_based # uniform/num_intercations/loss_based/pos_label_loss_based

# Optimization params
is_pretrained: true # Use imagenet pre trained model
cf_loss_type: exp # triplet/exp
batch_size: 256
weight_decay: 1e-5
lr: 1e-1
milestones: [65, 99]
epochs: 100

label_weight: 1.0 # The loss weight for binary label loss
cf_weight: 2.0 # The loss weight for cf vectors
cf_topk_loss_ratio: 1.0 # Consider only items with the lowest loss in the batch. 1.0 means consider all

# Flow params
is_debug: false
gpu: 0

hydra:
  run:
    dir: ../outputs/${category}/train_model_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ../outputs/${category}/train_model_multirun_${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}_cf_weight=${cf_weight}_labeled_ratio=${labeled_ratio}
# python train_model.py -m category=Toys_and_Games cf_weight=0.0,2.0 labeled_ratio=0.4,0.6,0.8,0.9,1.0
# python train_model.py category=Toys_and_Games cf_weight=2.5 labeled_ratio=1.0 confidence_type=pos_label_loss_based batch_size=256
