# Data params
category: Clothing_Shoes_and_Jewelry
cf_vector_df_path: ../outputs/train_recommender_Clothing_Shoes_and_Jewelry_20211019_092258/cf_df.pkl
train_df_path: ../outputs/process_label_Clothing_Shoes_and_Jewelry_20211019_120707/df_train_with_pos.pkl
test_df_path: ../outputs/process_label_Clothing_Shoes_and_Jewelry_20211019_120707/df_test_with_pos.pkl

# Dataset params
seed: 1234
num_workers: 4
labeled_ratio: 1.0 # The ratio fo the traninig set to contain label

# Optimization params
batch_size: 128

# CF pretraining
cf_training: 
  is_pretrained: true # Use imagenet pre trained model
  weight_decay: 1e-5
  lr: 1e-1
  milestones: [55] 
  epochs:  85
  cf_topk_loss_ratio: 1.0 # Consider only items with the lowest loss in the batch. 1.0 means consider all
  cf_weight: 1.0  # The loss weight for cf vectors
  label_weight: 0.0
  recall_at_k: []
  cf_loss_type: triplet

# Training with labels
label_training: 
  weight_decay: 1e-5
  lr: 1e-1
  milestones: [55] 
  epochs:  85 
  cf_topk_loss_ratio: 1.0 # Consider only items with the lowest loss in the batch. 1.0 means consider all
  cf_weight: 0.0  # The loss weight for cf vectors
  label_weight: 1.0
  recall_at_k: [3, 5, 10]
  cf_loss_type: triplet


# Flow params
is_debug: false
gpu: 0

hydra:
  run:
    dir: ../outputs/train_model_with_cf_pretraining_${category}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ../outputs/train_model_with_cf_pretraining_multirun_${category}_${now:%Y%m%d_%H%M%S}
    subdir: train_model_with_cf_pretraining_${category}_${now:%Y%m%d_%H%M%S}_${hydra.job.num}

# python train_model_with_cf_pretraining.py 