# Data params
category: Beauty # Clothing_Shoes_and_Jewelry/Home_and_Kitchen/Toys_and_Games
cf_vector_df_path: ../outputs/${category}/cf_df.pkl
train_df_path: ../outputs/${category}/df_train.pkl
test_df_path: ../outputs/${category}/df_test.pkl

# Dataset params
seed: 1234
num_workers: 4
labeled_ratio: 1.0 # The ratio fo the traninig set to contain label
recall_at_k: [3, 5]
is_use_bias: true
is_use_num_intercations: false

# Optimization params
batch_size: 512
weight_decay: 1e-5
lr: 1e-1
milestones: [80,95]
epochs: 100

# Flow params
is_debug: false
gpu: 0


is_pretrained: false

hydra:
  run:
    dir: ../outputs/${category}/train_model_cf_based_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ../outputs/${category}/train_model_cf_based_multirun_${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.num}

# python train_model_cf_based.py category=Beauty